services:
  backend:
    build: .
    container_name: epicplay_backend
    ports:
      - "${PORT}:${PORT}"  
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - db
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 30s npm run dev"

  db:
    image: mysql:8.0
    container_name: epicplay_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
